# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 025315169615b523a176acec0803c65777992aa7eb7eaf4e97ef223e09c14dd4c949f4a476a0869ec948c47ca9aee188303b033148edc1d3aa5b54fa31155e78

test:
  secret_key_base: 7924e6aa64a36d6f7838ff17f86acbecda6bebd15cc2d3a2922bcc6321cdbcd2a695716c4a5f484f9fb2bc774abf8d24bb61ea812cbe54bb59454869b28a19b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
